package icons;

import com.intellij.openapi.util.IconLoader;
import consulo.ui.image.Image;

/**
 * NOTE THIS FILE IS AUTO-GENERATED by the build/scripts/icons.gant
 * Don't repeat mistakes of others ;-)
 */
public class JetgroovyIcons
{
	private static Image load(String path)
	{
		return IconLoader.getIcon(path, JetgroovyIcons.class);
	}

	public static class Griffon
	{
		public static final Image Griffon_icon_24x24 = load("/icons/griffon/griffon-icon-24x24.png"); // 24x24
		public static final Image Griffon = load("/icons/griffon/griffon.png"); // 16x16
		public static final Image GriffonToolWindow = load("/icons/griffon/griffonToolWindow.png"); // 13x13
	}

	public static class Groovy
	{
		public static final Image AbstractClass = load("/icons/groovy/abstractClass.png"); // 16x16
		public static final Image AnnotationType = load("/icons/groovy/annotationType.png"); // 16x16
		public static final Image Ant_task = load("/icons/groovy/ant_task.png"); // 16x16
		public static final Image Class = load("/icons/groovy/class.png"); // 16x16
		public static final Image Def = load("/icons/groovy/def.png"); // 16x16
		public static final Image DynamicProperty = load("/icons/groovy/dynamicProperty.png"); // 16x16
		public static final Image DynamicProperty_13 = load("/icons/groovy/dynamicProperty_13.png"); // 13x13
		public static final Image Enum = load("/icons/groovy/enum.png"); // 16x16
		public static final Image Field = load("/icons/groovy/field.png"); // 16x16
		public static final Image Gant_16x16 = load("/icons/groovy/gant_16x16.png"); // 16x16
		public static final Image Gant_sdk = load("/icons/groovy/gant_sdk.png"); // 16x16
		public static final Image Gant_target = load("/icons/groovy/gant_target.png"); // 16x16
		public static final Image Groovy_13x13 = load("/icons/groovy/groovy_13x13.png"); // 13x13
		public static final Image Groovy_16x16 = load("/icons/groovy/groovy_16x16.png"); // 16x16
		public static final Image Groovy_32x32 = load("/icons/groovy/groovy_32x32.png"); // 32x32
		public static final Image GroovyDoc = load("/icons/groovy/GroovyDoc.png"); // 16x16
		public static final Image Interface = load("/icons/groovy/interface.png"); // 16x16
		public static final Image Method = load("/icons/groovy/method.png"); // 16x16
		public static final Image Trait = load("/icons/groovy/trait.png"); // 16x16
		public static final Image Property = load("/icons/groovy/property.png"); // 16x16
		public static final Image Variable = load("/icons/groovy/variable.png"); // 16x16
	}

	public static class Mvc
	{
		public static final Image Action_method = load("/icons/mvc/action_method.png"); // 16x16
		public static final Image Config_folder_closed = load("/icons/mvc/config_folder_closed.png"); // 16x16
		public static final Image Controller = load("/icons/mvc/controller.png"); // 16x16
		public static final Image Domain_class = load("/icons/mvc/domain_class.png"); // 16x16
		public static final Image Groovy_mvc_plugin = load("/icons/mvc/groovy_mvc_plugin.png"); // 16x16
		public static final Image ModelsNode = load("/icons/mvc/modelsNode.png"); // 16x16
		public static final Image Service = load("/icons/mvc/service.png"); // 16x16
	}
}
