/**
 * @author VISTALL
 * @since 25/02/2023
 */
open module org.intellij.groovy.psi {
  requires transitive consulo.ide.api;
  requires transitive consulo.java.language.api;
  requires transitive consulo.java.language.impl;

  requires org.apache.groovy;

  requires com.intellij.xml;
  
  // TODO remove in future
  requires java.desktop;
  
  exports consulo.groovy.module.extension;
  exports consulo.groovy.psi.icon;
  exports org.jetbrains.plugins.groovy;
  exports org.jetbrains.plugins.groovy.annotator;
  exports org.jetbrains.plugins.groovy.codeInsight;
  exports org.jetbrains.plugins.groovy.codeInspection.utils;
  exports org.jetbrains.plugins.groovy.config;
  exports org.jetbrains.plugins.groovy.dsl;
  exports org.jetbrains.plugins.groovy.dsl.dsltop;
  exports org.jetbrains.plugins.groovy.dsl.holders;
  exports org.jetbrains.plugins.groovy.dsl.psi;
  exports org.jetbrains.plugins.groovy.dsl.toplevel;
  exports org.jetbrains.plugins.groovy.dsl.toplevel.scopes;
  exports org.jetbrains.plugins.groovy.editor;
  exports org.jetbrains.plugins.groovy.extensions;
  exports org.jetbrains.plugins.groovy.findUsages;
  exports org.jetbrains.plugins.groovy.intentions.utils;
  exports org.jetbrains.plugins.groovy.lang.completion.closureParameters;
  exports org.jetbrains.plugins.groovy.lang.groovydoc.lexer;
  exports org.jetbrains.plugins.groovy.lang.groovydoc.parser;
  exports org.jetbrains.plugins.groovy.lang.groovydoc.parser.elements;
  exports org.jetbrains.plugins.groovy.lang.groovydoc.parser.parsing;
  exports org.jetbrains.plugins.groovy.lang.groovydoc.psi;
  exports org.jetbrains.plugins.groovy.lang.groovydoc.psi.api;
  exports org.jetbrains.plugins.groovy.lang.groovydoc.psi.impl;
  exports org.jetbrains.plugins.groovy.lang.lexer;
  exports org.jetbrains.plugins.groovy.lang.parser;
  exports org.jetbrains.plugins.groovy.lang.parser.parsing.auxiliary;
  exports org.jetbrains.plugins.groovy.lang.parser.parsing.auxiliary.annotations;
  exports org.jetbrains.plugins.groovy.lang.parser.parsing.auxiliary.modifiers;
  exports org.jetbrains.plugins.groovy.lang.parser.parsing.auxiliary.parameters;
  exports org.jetbrains.plugins.groovy.lang.parser.parsing.statements;
  exports org.jetbrains.plugins.groovy.lang.parser.parsing.statements.blocks;
  exports org.jetbrains.plugins.groovy.lang.parser.parsing.statements.constructor;
  exports org.jetbrains.plugins.groovy.lang.parser.parsing.statements.declaration;
  exports org.jetbrains.plugins.groovy.lang.parser.parsing.statements.expressions;
  exports org.jetbrains.plugins.groovy.lang.parser.parsing.statements.expressions.arguments;
  exports org.jetbrains.plugins.groovy.lang.parser.parsing.statements.expressions.arithmetic;
  exports org.jetbrains.plugins.groovy.lang.parser.parsing.statements.expressions.primary;
  exports org.jetbrains.plugins.groovy.lang.parser.parsing.statements.expressions.regex;
  exports org.jetbrains.plugins.groovy.lang.parser.parsing.statements.expressions.relational;
  exports org.jetbrains.plugins.groovy.lang.parser.parsing.statements.imports;
  exports org.jetbrains.plugins.groovy.lang.parser.parsing.statements.typeDefinitions;
  exports org.jetbrains.plugins.groovy.lang.parser.parsing.statements.typeDefinitions.members;
  exports org.jetbrains.plugins.groovy.lang.parser.parsing.toplevel;
  exports org.jetbrains.plugins.groovy.lang.parser.parsing.toplevel.packaging;
  exports org.jetbrains.plugins.groovy.lang.parser.parsing.types;
  exports org.jetbrains.plugins.groovy.lang.parser.parsing.util;
  exports org.jetbrains.plugins.groovy.lang.psi;
  exports org.jetbrains.plugins.groovy.lang.psi.api;
  exports org.jetbrains.plugins.groovy.lang.psi.api.auxiliary;
  exports org.jetbrains.plugins.groovy.lang.psi.api.auxiliary.modifiers;
  exports org.jetbrains.plugins.groovy.lang.psi.api.auxiliary.modifiers.annotation;
  exports org.jetbrains.plugins.groovy.lang.psi.api.formatter;
  exports org.jetbrains.plugins.groovy.lang.psi.api.signatures;
  exports org.jetbrains.plugins.groovy.lang.psi.api.statements;
  exports org.jetbrains.plugins.groovy.lang.psi.api.statements.arguments;
  exports org.jetbrains.plugins.groovy.lang.psi.api.statements.blocks;
  exports org.jetbrains.plugins.groovy.lang.psi.api.statements.branch;
  exports org.jetbrains.plugins.groovy.lang.psi.api.statements.clauses;
  exports org.jetbrains.plugins.groovy.lang.psi.api.statements.expressions;
  exports org.jetbrains.plugins.groovy.lang.psi.api.statements.expressions.arithmetic;
  exports org.jetbrains.plugins.groovy.lang.psi.api.statements.expressions.literals;
  exports org.jetbrains.plugins.groovy.lang.psi.api.statements.expressions.path;
  exports org.jetbrains.plugins.groovy.lang.psi.api.statements.params;
  exports org.jetbrains.plugins.groovy.lang.psi.api.statements.typedef;
  exports org.jetbrains.plugins.groovy.lang.psi.api.statements.typedef.members;
  exports org.jetbrains.plugins.groovy.lang.psi.api.toplevel;
  exports org.jetbrains.plugins.groovy.lang.psi.api.toplevel.imports;
  exports org.jetbrains.plugins.groovy.lang.psi.api.toplevel.packaging;
  exports org.jetbrains.plugins.groovy.lang.psi.api.types;
  exports org.jetbrains.plugins.groovy.lang.psi.api.util;
  exports org.jetbrains.plugins.groovy.lang.psi.controlFlow;
  exports org.jetbrains.plugins.groovy.lang.psi.controlFlow.impl;
  exports org.jetbrains.plugins.groovy.lang.psi.dataFlow;
  exports org.jetbrains.plugins.groovy.lang.psi.dataFlow.reachingDefs;
  exports org.jetbrains.plugins.groovy.lang.psi.dataFlow.types;
  exports org.jetbrains.plugins.groovy.lang.psi.expectedTypes;
  exports org.jetbrains.plugins.groovy.lang.psi.impl;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.auxiliary;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.auxiliary.annotation;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.auxiliary.modifiers;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.search;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.signatures;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.statements;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.statements.arguments;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.statements.blocks;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.statements.branch;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.statements.clauses;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.arithmetic;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.binaryCalculators;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.bitwise;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.literals;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.logical;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.path;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.regex;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.relational;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.types;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.statements.params;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.statements.typedef;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.statements.typedef.enumConstant;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.statements.typedef.members;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.synthetic;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.toplevel.imports;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.toplevel.packaging;
  exports org.jetbrains.plugins.groovy.lang.psi.impl.types;
  exports org.jetbrains.plugins.groovy.lang.psi.patterns;
  exports org.jetbrains.plugins.groovy.lang.psi.stubs;
  exports org.jetbrains.plugins.groovy.lang.psi.stubs.elements;
  exports org.jetbrains.plugins.groovy.lang.psi.stubs.index;
  exports org.jetbrains.plugins.groovy.lang.psi.typeEnhancers;
  exports org.jetbrains.plugins.groovy.lang.psi.util;
  exports org.jetbrains.plugins.groovy.lang.resolve;
  exports org.jetbrains.plugins.groovy.lang.resolve.ast;
  exports org.jetbrains.plugins.groovy.lang.resolve.noncode;
  exports org.jetbrains.plugins.groovy.lang.resolve.processors;
  exports org.jetbrains.plugins.groovy.refactoring.introduce;
  exports org.jetbrains.plugins.groovy.util;
}